#!/usr/bin/python

from hsrb_interface import robot
from std_srvs.srv import Trigger, TriggerResponse
import rospy

def trigger(req):
    rospy.loginfo("Sleeping for mock wrist trigger...")
    rospy.sleep(5)
    return TriggerResponse(success=True)

def wrist_trigger_server():
    rospy.init_node('wrist_trigger_node', anonymous=True)
    rospy.Service('wrist_trigger', Trigger, trigger) 
    rospy.spin()

if __name__ == '__main__':
    wrist_trigger_server()

